x-common-service: &common
  init: true
  volumes:
    - ../courses:/lectures
    - home:/home
  expose:
    - "22"

services:
  head-instructor:
    build:
      context: ./docker/csc466/head-instructor
      tags:
        - "csc466:head-instructor"
    <<: *common
    image: csc466:head-instructor
    ports:
      - "18088:8088"
      - "18000:8000"
      - "2222:22"
    volumes:
      - ../grading-scripts:/grading-scripts
      - ../d2l:/d2l
    hostname: head
    container_name: head
    deploy:
      resources:
        limits:
          cpus: 4.0

  head-student:
    build:
      context: ./docker/csc466/head-student
      tags:
        - "csc466:head-student"
    image: csc466:head-student
    <<: *common
    ports:
      - "18088:8088"
      - "18000:8000"
      - "2222:22"
    hostname: head
    container_name: head
    deploy:
      resources:
        limits:
          cpus: 4.0

  compute01:
    image: csc466:base
    <<: *common
    expose:
      - "22"
    hostname: compute01
    container_name: compute01
    deploy:
      resources:
        limits:
          cpus: 2.0

  compute02:
     image: csc466:base
    <<: *common
    hostname: compute02
    container_name: compute02
    deploy:
      resources:
        limits:
          cpus: 2.0
          
volumes:
  home:
