services:
  base:
    build:
      context: ./docker/base
    image: linhbngo/onering-amd64:base
    command: /bin/bash -c exit

  csc331:
    build:
      context: ./docker/csc331
    image: linhbngo/onering-amd64:csc331
    container_name: csc331
    volumes:
      - .:/workspace
      - home:/home
    ports:
      - "18088:8088"
      - "22331:22"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    mem_limit: 2048m
    cpus: 2.0

  466-cpn01:
    build:
      context: ./docker/csc466
    image: linhbngo/onering-amd64:csc466
    container_name: cpn01
    volumes:
      - .:/workspace
      - home:/home
    ports:
      - "22"
    mem_limit: 2048m
    cpus: 2.0

  466-cpn02:
    build:
      context: ./docker/csc466
    image: linhbngo/onering-amd64:csc466
    container_name: cpn02
    volumes:
      - .:/workspace
      - home:/home
    ports:
      - "22"
    mem_limit: 2048m
    cpus: 2.0

volumes:
  home:
