x-common-service: &common
  init: true
  ports:
    - "18080:8080" # spark-master webui
    - "18088:8088" # code-server
    - "14040:4040" # application ui
  environment:
    - "SPARK_LOCAL_IP=spark-master"
  volumes:
    - ./data:/data
    - ./notebooks:/notebooks
    
services:
  467-instructor:
    <<: *common
    build:
      context: ./docker/csc467/master-instructor
      tags:
        - "csc467:master-instructor"
    image: csc467:master-instructor
    ports:
      - "18888:8888" # jupyter server
      - "18088:8088" # code-server
    volumes:
      - ../courses:/lectures # courses is a github repo containing lecture materials
      - ../grading-scripts:/grading-scripts
      - ../d2l:/d2l
    
    hostname: spark-master
    container_name: spark-master

  467-student:
    <<: *common
    build:
      context: ./docker/csc467/master-student
      tags:
        - "csc467:master-student"
    image: csc467:master-student
    volumes:
      - ./data:/data
      - ./notebooks:/notebooks
    hostname: spark-master
    container_name: spark-master

  # This service will depend on either master-instructor or master-student    
  467-worker:
    build:
      context: ./docker/csc467/worker
      tags:
        - "csc467:worker"
    init: true
    image: csc467:worker
    ports:
      - "8081"
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=128m
      - SPARK_EXECUTOR_MEMORY=256m
