x-common-service: &common
  init: true
  volumes:
    - ../courses:/lectures
    - home:/home
  expose:
    - "22"
  cap_add:
    - SYS_PTRACE
  security_opt:
    - seccomp=unconfined

services:
  head-instructor:
    build:
      context: ./docker/csc331/head-instructor
      tags:
        - "csc331:head-instructor"
    <<: *common
    image: csc331:head-instructor
    ports:
      - "18088:8088"
      - "18000:8000"
      - "2222:22"
    volumes:
      - ../grading-scripts:/grading-scripts
      - ../d2l:/d2l
    hostname: head
    container_name: head
    deploy:
      resources:
        limits:
          cpus: 2.0

  head-student:
    build:
      context: ./docker/csc331/head-student
      tags:
        - "csc331:head-student"
    image: csc331:head-student
    <<: *common
    ports:
      - "18088:8088"
      - "18000:8000"
      - "2222:22"
    hostname: head
    container_name: head
    deploy:
      resources:
        limits:
          cpus: 2.0
          
volumes:
  home:
